name: Docker Image CI

on:
  push:
    branches:
      - 'master'

jobs:
  docker-base-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            jimetevenard/code-env:base
  docker-env-images:
    needs: docker-base-image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor:
        - xml-relaxng
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.flavor }}
          push: true
          tags: jimetevenard/code-env:${{ matrix.flavor }}
